fileurl<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(fileurl,"power_consumption.zip")
unzip("power_consumption.zip")
data_file<-read.table("household_power_consumption.txt",header = TRUE,sep = ";",na.strings = "?",stringsAsFactors = FALSE)
data_file$Date<-strptime(data_file$Date,"%d/%m/%Y")
subset_data<-subset(data_file,Date>="2007-02-01" & Date<="2007-02-02")
subset_data$Date_Time<-strptime(paste(subset_data$Date,subset_data$Time,sep = " "),"%Y-%m-%d %H:%M:%S")
png(file="plot2.png",height=480,width=480)
plot(subset_data$Date_Time,subset_data$Global_active_power,type="l",xlab = "",ylab = "Global Active Power (kilowatts)")
dev.off()
